runtime: python312  # 或你使用的 Python 版本
service: update-task-runner # (建議) 給服務取個名字
instance_class: F1  # 或其他實例類型

# --- 直接執行 Python 腳本 ---
entrypoint: python update-stocks.py）

# 處理靜態檔案（如果有，例如 index.html）
handlers:
  - url: /static
    static_dir: static  # 如果您有靜態檔案，放在 static 資料夾

  - url: /.*
    script: auto  # 動態請求由 Flask 處理

# 確保依賴在部署時安裝cd 
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10